Feat/image chart
SwanHubX/SwanLab pull request #139
Opened 2024-01-04 06:30 UTC by xiaolin199912

## Description

1. 增加基于BaseType的Image类（支持String、numpy array和PIL.Image三种输入类型）
2. 修改测试代码：「运行实验」

2024-01-04 06:53 UTC, SAKURA-CAT commented on test/create_experiment.py
> +class Image(sw.data.BaseType):
尝试把这个删了然后使用swanlab提供的Image对象

2024-01-04 07:19 UTC, SAKURA-CAT requested changes

2024-01-04 07:19 UTC, SAKURA-CAT commented on swanlab/data/modules/image.py
> +    def extract_path_layers(self, absolute_path: str) -> str:
不可以使用split方式，因为windows和类unix的路径表示方式不一样。
事实上settings提供了一个root_dir参数，代表“当前运行的根目录的绝对路径”，static_dir是通过它计算得到的，你可以反向计算回去

2024-01-04 07:20 UTC, SAKURA-CAT requested changes

2024-01-04 07:20 UTC, SAKURA-CAT commented on test/create_experiment.py
> +class Image(sw.data.BaseType):
尝试把这个删了然后使用swanlab提供的Image对象

2024-01-04 07:23 UTC, SAKURA-CAT commented
> ## Description
> 1. 增加基于BaseType的Image类（支持String、numpy array和PIL.Image三种输入类型）
> 2. 修改测试代码：「运行实验」
> 
> Closes #121

String输入类型是什么，base64吗

2024-01-04 07:43 UTC, xiaolin199912 commented
> > ## Description
> > 
> > 1. 增加基于BaseType的Image类（支持String、numpy array和PIL.Image三种输入类型）
> > 2. 修改测试代码：「运行实验」
> > 
> > Closes #121
> 
> String输入类型是什么，base64吗

不是，是图像的路径

2024-01-24 12:37 UTC, closed without merging

2024-01-24 12:37 UTC, xiaolin199912 commented
image_chart的内容已归到audio_chart分支，