Feat name limit
SwanHubX/SwanLab pull request #158
Opened 2024-01-06 13:40 UTC by Feudalman

## Description

Add infomation check both in server and web js

Closes: #116

2024-01-06 14:39 UTC, SAKURA-CAT requested changes

2024-01-06 14:39 UTC, SAKURA-CAT commented on swanlab/server/api/experiment.py
> +    check_exp_name_format(body["name"], False)
这你没判断一下错误？

2024-01-06 14:39 UTC, SAKURA-CAT commented on swanlab/server/api/project.py
> +from ...utils.file import check_description
改个名啊哥们，check_desc_format，和其他几个对应起来

2024-01-06 14:39 UTC, SAKURA-CAT commented on swanlab/utils/file.py
> +def check_description(description: str, auto_cut: bool):
改个名改个名

2024-01-07 03:04 UTC, Feudalman commented on swanlab/server/api/project.py
> +from ...utils.file import check_description
改了 我的抗哥

2024-01-07 03:31 UTC, SAKURA-CAT approved these changes

2024-01-07 03:32 UTC, merged