Feature/text chart
SwanHubX/SwanLab pull request #337
Opened 2024-02-21 11:13 UTC by Feudalman

## Description

Text Chart

Closes: #323

2024-02-21 11:14 UTC, Feudalman commented
更新图表时有一些问题，正在解决

2024-02-26 14:09 UTC, xiaolin199912 approved these changes

2024-02-28 07:37 UTC, SAKURA-CAT requested changes

2024-02-28 07:37 UTC, SAKURA-CAT commented on swanlab/server/router/media.py
改为统一接口，由前端完成二进制数据展示

2024-02-28 13:25 UTC, SAKURA-CAT approved these changes

2024-02-28 13:25 UTC, merged