feat: export line chart as png
SwanHubX/SwanLab pull request #544
Opened 2024-05-14 08:13 UTC by Feudalman

将折线图表导出为png

2024-05-14 08:20 UTC, SAKURA-CAT requested changes

2024-05-14 08:20 UTC, SAKURA-CAT commented on vue/src/charts/components/ChartContainer.vue
> +  <SLModal class="pt-5 overflow-hidden" max-w="800" v-model="downloadModal" escExit>
新搞个组件

2024-05-14 08:20 UTC, SAKURA-CAT commented on vue/src/charts/components/ChartContainer.vue
> +  <SLModal class="pt-5 overflow-hidden" max-w="800" v-model="downloadModal" escExit>
因为后续操作很复杂，不要在这里写

2024-05-14 08:20 UTC, Feudalman commented on vue/src/charts/components/ChartContainer.vue
> +  <SLModal class="pt-5 overflow-hidden" max-w="800" v-model="downloadModal" escExit>
可以的

2024-05-14 08:20 UTC, SAKURA-CAT commented on vue/src/charts/components/ChartContainer.vue
> +                  v-if="chart?.type === 'default' || chart?.type === 'line'"
使用一个computed函数解决

2024-05-14 08:41 UTC, SAKURA-CAT requested changes

2024-05-14 08:41 UTC, SAKURA-CAT commented on vue/src/charts/components/ChartContainer.vue
> +                <SLMenuItem class="py-1" v-if="isLineChart" @click="downloadModal = true"> 下载 </SLMenuItem>
where is your i18n

2024-05-14 08:42 UTC, Feudalman commented on vue/src/charts/components/ChartContainer.vue
> +                <SLMenuItem class="py-1" v-if="isLineChart" @click="downloadModal = true"> 下载 </SLMenuItem>
don't ji

2024-05-17 11:05 UTC, SAKURA-CAT approved these changes

2024-05-17 11:07 UTC, merged