修复win
SwanHubX/SwanLab pull request #641
Opened 2024-06-26 14:43 UTC by ShaohonChen

## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please
mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/SwanHubX/SwanLab/issues)
for this change. If not, please create an issue before you create this PR, unless the fix is very small.

Not adhering to this guideline will result in the PR being closed.

2024-06-26 15:55 UTC, SAKURA-CAT requested changes

2024-06-26 15:55 UTC, SAKURA-CAT commented on swanlab/data/formater.py
> +def check_unique_on_case_insensitive(names: List[str]):
为什么要大小写不敏感

2024-06-26 15:55 UTC, SAKURA-CAT commented on swanlab/data/formater.py
> +def check_win_reserved_folder_name(folder_name: str, auto_fix=True) -> str:
应该加测试

2024-06-26 16:16 UTC, Zeyi-Lin commented on swanlab/data/formater.py
> +def check_unique_on_case_insensitive(names: List[str]):
似乎因为Windows的文件夹大小写不敏感

2024-06-27 11:17 UTC, SAKURA-CAT commented on swanlab/data/formater.py
> +def check_unique_on_case_insensitive(names: List[str]):
好吧，看来目前方案确实需要改进

2024-06-27 11:46 UTC, ShaohonChen commented on swanlab/data/formater.py
> +def check_win_reserved_folder_name(folder_name: str, auto_fix=True) -> str:
这个测试是？

2024-06-27 11:48 UTC, ShaohonChen commented on swanlab/data/formater.py
> +def check_win_reserved_folder_name(folder_name: str, auto_fix=True) -> str:
是指我统一写一个测试脚本是吗

2024-06-27 12:52 UTC, ShaohonChen commented
增加了test脚本 @SAKURA-CAT 麻烦codereview一下

2024-06-27 13:02 UTC, SAKURA-CAT approved these changes

2024-06-27 13:03 UTC, merged