bugfix/config_json_serializable
SwanHubX/SwanLab pull request #671
Opened 2024-08-11 09:37 UTC by Zeyi-Lin

问题发现：在运行fastai测试脚本时，config报错，原因是框架的配置dict中带了很多函数和类。
修复：将`json_serializable`函数从与列出的类型不匹配就raise错误，改为返回str(obj)，若仍出错就rasie TypeError。

2024-08-11 10:14 UTC, SAKURA-CAT commented
str(obj)应该不太行，因为config应该返回一个字典

2024-08-11 10:15 UTC, SAKURA-CAT requested changes

2024-08-11 10:15 UTC, SAKURA-CAT commented on swanlab/data/run/config.py
> +        return str(obj)
str(obj)应该不太行，因为config应该返回一个字典

2024-08-11 10:27 UTC, Zeyi-Lin commented on swanlab/data/run/config.py
> +        return str(obj)
在外部增加了类型判断

2024-08-11 10:30 UTC, SAKURA-CAT requested changes

2024-08-11 10:30 UTC, SAKURA-CAT commented on swanlab/data/run/config.py
> +            raise TypeError(f"config: {config} is not a json serialized dict")
这里直接改成如果是字符串就改为字典会好一些我觉得

2024-08-11 14:30 UTC, Zeyi-Lin commented on swanlab/data/run/config.py
> +            raise TypeError(f"config: {config} is not a json serialized dict")
我想了想，主要是这两个方面：
1. 如果用户扔了一个swanlab.init(config=1)进来，实际应该报个错给用户，之前的代码这类问题
2. 如果要改成字典的话，字符串只有value没有key，还需要定义一个默认key

2024-08-11 14:44 UTC, SAKURA-CAT commented on swanlab/data/run/config.py
> +            raise TypeError(f"config: {config} is not a json serialized dict")
我觉得都可以。那你有空把测试用例加一下吧，主要两方面：

1. fastai的测试用例
2. 错误情况，比如init(config=1)这种

2024-08-13 09:57 UTC, Zeyi-Lin commented on swanlab/data/run/config.py
> +            raise TypeError(f"config: {config} is not a json serialized dict")
修改了一些代码。
针对提到的两方面：
1. fastai的测试用例在test/integration/fastai/fastai_train.py
2.已补充pytest的错误情况

2024-08-13 10:01 UTC, SAKURA-CAT approved these changes

2024-08-13 10:02 UTC, merged